<a href="https://colab.research.google.com/github/maha-sobuh/ML-GSG-/blob/main/gettingStarted.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

**Task 1 : Array Basics (Numpy)**

In [ ]:
#1.1.1
arr1=np.arange(0,10)

In [ ]:
#1.1.2
np.random.randint(1,100,(3,3))

array([[11, 69, 27],
       [10, 53, 42],
       [33, 90, 12]])

In [ ]:
#1.2
arr1.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [ ]:
#1.3
print(arr1.shape)
print(arr1.size)
print(arr1.dtype)

(10,)
10
int64


**Task 2 : Data Manipulation (Pandas)**

In [ ]:
#2.1
data = np.random.rand(5,3)
col = ['A','B','C']
df=pd.DataFrame(data,columns=col)
df

A         B         C
0  0.424535  0.752310  0.447894
1  0.474052  0.300228  0.266328
2  0.698239  0.857938  0.510720
3  0.022429  0.126720  0.256815
4  0.052137  0.606688  0.492127

In [ ]:
#2.2.1
df.head(2)

A         B         C
0  0.424535  0.752310  0.447894
1  0.474052  0.300228  0.266328

In [ ]:
#2.2.2
means=df.mean()
print(means)

A    0.334278
B    0.528777
C    0.394777
dtype: float64


In [ ]:
#2.2.3
D=df['A']+df['B']
df['D']=D
df

A         B         C         D
0  0.424535  0.752310  0.447894  1.176845
1  0.474052  0.300228  0.266328  0.774280
2  0.698239  0.857938  0.510720  1.556177
3  0.022429  0.126720  0.256815  0.149149
4  0.052137  0.606688  0.492127  0.658825

In [ ]:
con = df.A>50
df[con]

Empty DataFrame
Columns: [A, B, C, D]
Index: []

In [ ]:
sorted_df=df.sort_values(by='C',ascending=False)
sorted_df

A         B         C         D
2  0.698239  0.857938  0.510720  1.556177
4  0.052137  0.606688  0.492127  0.658825
0  0.424535  0.752310  0.447894  1.176845
1  0.474052  0.300228  0.266328  0.774280
3  0.022429  0.126720  0.256815  0.149149

**Task 3 : Numerical Computations (Numpy)**

In [ ]:
#3.1.1
a=np.random.randint(100,None,5)
b=np.random.randint(100,None,5)
print(a)
print(b)

[35  8 29 35 47]
[25 79 79 41  1]


In [ ]:
#3.1.2
a+b

array([ 60,  87, 108,  76,  48])

In [ ]:
a-b

array([ 10, -71, -50,  -6,  46])

In [ ]:
a*b

array([ 875,  632, 2291, 1435,   47])

In [ ]:
#3.2
print(a.mean())
print(a.sum())
print (a.std())

30.8
154
12.812493902437573
12.812493902437573


In [ ]:
#3.3
U=np.array([[3,5,3],[2,8,1]])
V=np.array([[4,2],[5,11],[9,12]])
U.dot(V)

array([[ 64,  97],
       [ 57, 104]])

**Task 4 **

In [ ]:
#4.1
temp=np.random.uniform(10,30,7)
avg= temp.mean()
days=temp>avg
print(temp[days])

[26.13180492 18.52723207 28.06694993]


In [ ]:
#4.2.1
Days=['MON','TUE','WED','THU','FRI','SAT','SUN']
df=pd.DataFrame({'Day':Days,'Temperature':temp})
df

Day  Temperature
0  MON    26.131805
1  TUE    13.190307
2  WED    18.527232
3  THU    11.202559
4  FRI    11.141143
5  SAT    15.905318
6  SUN    28.066950

In [ ]:
#4.2.2
max_day=df[df['Temperature']==df['Temperature'].max()]
max_day

Day  Temperature
6  SUN     28.06695

In [ ]:
#4.3
stock_prices = np.random.uniform(100, 500, 5)
Days=['MON','TUE','WED','THU','FRI']
df = pd.DataFrame({
    'Day': Days,
    'Stock Price': stock_prices
})

df['Price Change'] = df['Stock Price'].pct_change() * 100
df

Day  Stock Price  Price Change
0  MON   438.333394           NaN
1  TUE   139.080191    -68.270683
2  WED   313.865518    125.672338
3  THU   297.650657     -5.166181
4  FRI   121.151088    -59.297557