In [80]:
import numpy as np

In [81]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [82]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [83]:
np.full(10,2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [84]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [85]:
np.arange(3,10)

array([3, 4, 5, 6, 7, 8, 9])

In [86]:
#returns array filled with 11 number between 0 , 7
np.linspace(0,7,11) 


array([0. , 0.7, 1.4, 2.1, 2.8, 3.5, 4.2, 4.9, 5.6, 6.3, 7. ])

In [87]:
my_list=[1,2,4,6,7] 

In [88]:
#sometimes it's better to use array than list 
my_array=np.array(my_list)

In [89]:
my_array=np.array([1,4,57,8,9,5])

In [90]:
sec_element=my_array[1]

In [91]:
last_element = my_array[-1]

In [92]:
print(sec_element) 
print(last_element)

4
5


In [93]:
print(my_array[-2])

9


In [94]:
subset_array=my_array[1:4]

In [95]:
subset_array

array([ 4, 57,  8])

In [96]:
#2D array 
arr=np.array([[1,2,3] , [4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [97]:
arr1=np.array([[1,2],[3,4]]) 
arr2=np.array([[5,6],[7,8]]) 
print (arr1) 
print (arr2) 

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


In [98]:
print (arr1+arr2)

[[ 6  8]
 [10 12]]


In [99]:
print (arr1*arr2)

[[ 5 12]
 [21 32]]


In [100]:
#summation of all elements 
sum_val=np.sum(arr1) 
sum_val

np.int64(10)

In [101]:
mean_val=np.mean(arr1,axis=0) 
mean_val

array([2., 3.])

In [102]:
mean_val=np.mean(arr1,axis=1) 
mean_val

array([1.5, 3.5])

In [103]:
print (arr1[0,1])

2


In [104]:
#accesing to row 
row=arr1[0 , : ] 
row

array([1, 2])

In [105]:
#accesing to multiple rows 
arr=np.array([[1,2,3] , [4,5,6] , [7,8,9]] ) 
rows = arr[[0,2] , : ] 
rows 

array([[1, 2, 3],
       [7, 8, 9]])

In [118]:
random_integers = np.random.randint (10,size=(2,5))
random_integers 

array([[0, 1, 1, 8, 2],
       [8, 6, 9, 0, 5]], dtype=int32)

In [143]:
random_normal = np.random.normal(size=(3,2,3))
random_normal

array([[[ 0.56779976, -2.34189012,  0.86231505],
        [ 0.08919341,  1.53159941,  0.23593144]],

       [[-1.1177209 ,  0.07238898,  0.02810292],
        [ 0.34706708, -0.70610016, -0.93663242]],

       [[ 2.66572103, -1.19243679,  0.21033872],
        [ 0.57184571,  0.90994736,  1.35821296]]])

In [147]:
random_floats = np.random.random((3,4))
random_floats 

array([[0.65293173, 0.24720725, 0.40970119, 0.98965682],
       [0.65493191, 0.50561982, 0.89703691, 0.93981398],
       [0.01682991, 0.44374658, 0.36761099, 0.32972389]])

In [146]:
np.random.rand(3,4)

array([[0.80614907, 0.64358636, 0.19305034, 0.92625726],
       [0.45536079, 0.01734641, 0.33339319, 0.18723181],
       [0.59335449, 0.56468116, 0.36896668, 0.18133093]])

.rand and .random have the same work 
but .random give us the ability to use a tuple as a size 

In [148]:
arr=np.array([0,np.pi/2 , np.pi]) 
np.sin(arr)

array([0.0000000e+00, 1.0000000e+00, 1.2246468e-16])

In [149]:
np.exp(arr)

array([ 1.        ,  4.81047738, 23.14069263])